version: '3'
services:
  database-backup-manager:
    build: .
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    container_name: database-backup-manager
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: src/app.py
    ports:
      - 5001:5000
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    container_name: my_test_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  postgres:
    image: postgres:latest
    container_name: my_test_postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
      POSTGRES_USER: user
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    container_name: my_test_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
